<?php

namespace App\Services\WebsiteService;

use App\Enums\BlockCategoryEnum;
use App\Facades\FileService\UploadService;
use App\Models\Block;
use App\Models\Link;
use App\Models\ProjectLibrary;
use App\Models\ProjectSkill;
use Illuminate\Support\Str;

/**
 * @extends BlockService<Block>
 */
class ProjectService extends BlockService
{

    private function isProject(Block $block): bool
    {
        return $block->category === Str::slug(BlockCategoryEnum::PROJECTS->value);
    }
    /**
     * @param int $projectId
     * @return array
     */
    public function mapLinksModel(int $projectId): array
    {
        $link = Link::query()->where('project_id', $projectId)->first();
        return [
            'linkId' => $link->id,
            'github' => $link->github_url,
            'preview' => $link->preview_url,
        ];
    }

    /**
     * @param Block $block
     * @return array
     */
    public function mapBlockModel(Block $block): array {
        \assert($this->isProject($block));

        $skillsModel = [];
        $librariesModel = [];
        $linksModel = $this->mapLinksModel($block->id);

//        $links = $block->links()->first();
        $skills = $block->skills()->get();
        $libraries = $block->libraries()->get();

        foreach ($skills as $skill) {
            $skillsModel[] = parent::mapBlockModel($skill);
        }

        foreach ($libraries as $library) {
            $librariesModel[] = parent::mapBlockModel($library);
        }

        return [
            ...parent::mapBlockModel($block),
            'links' => $linksModel,
            'skills' => $skillsModel,
            'libraries' => $librariesModel,
        ];
    }

    /**
     * @param Block $block
     * @return array
     */
    public function mapLocaleBlock(Block $block): array
    {
        \assert($this->isProject($block));
        $skillsModel = [];
        $librariesModel = [];
        $linksModel = $this->mapLinksModel($block->id);

//        $links = $block->links()->first();
        $skills = $block->skills()->get();
        $libraries = $block->libraries()->get();

        foreach ($skills as $skill) {
            $skillsModel[] = parent::mapLocaleBlock($skill);
        }

        foreach ($libraries as $library) {
            $librariesModel[] = parent::mapLocaleBlock($library);
        }

        return [
            ...parent::mapLocaleBlock($block),
            'links' => $linksModel,
            'skills' => $skillsModel,
            'libraries' => $librariesModel,
        ];
    }

    private function storeSkills(array $data, int $projectId): void
    {
        $skills = $data['skills'];
        foreach ($skills as $skill) {
            $projectSkill = new ProjectSkill();
            $projectSkill->fill([
                'project_id' => $projectId,
                'skill_id' => $skill,
            ]);
            $projectSkill->save();
        }
    }

    private function storeLibraries(array $data, int $projectId): void
    {
        $libraries = $data['libraries'];
        foreach ($libraries as $library) {
            $projectLibrary = new ProjectLibrary();
            $projectLibrary->fill([
                'project_id' => $projectId,
                'library_id' => $library,
            ]);
            $projectLibrary->save();
        }
    }

    private function storeLinks(array $data, int $projectId) {
        $links = new Link();
        $links->fill([
            'project_id' => $projectId,
            'github_url' => $data['github'] ?? '',
            'preview_url' => $data['preview'],
        ]);
        $links->save();
    }

    /**
     * @param $data
     * @return array
     */
    public function storeBlock($data): array
    {
        $block = new Block();
//        $data = request()->all();
        $this->fillBlockForm($block);
        $block->save();
        //Store Translations:
        $this->storeTranslations($data, $block);
        //Store Files:
        //        2. Store File:
        if (array_key_exists('image', $data)) {
            $data['refId'] = $block->id;
            $data['refType'] = $this->reference;
            UploadService::saveFile($data, 'image', 'block');
        }
        $this->storeSkills($data, $block->id);
        $this->storeLibraries($data, $block->id);
        $this->storeLinks($data, $block->id);
        return $this->mapBlockModel($block); // TODO: Change the autogenerated stub
    }

    public function updateTranslations(array $data, Block $block)
    {
        parent::updateTranslations($data, $block);

        //Handle Skills:
        $block->skills()->sync($data['skills']);

        //Handle Libraries:
        $block->libraries()->sync($data['libraries']);

        //Handle Links:
        $link = $block->links()->where('project_id', $block->id)->first();
        if (!is_null($link)) {
            $link->fill([
                'github_url' => $data['github'] ?? '',
                'preview_url' => $data['preview'],
            ]);
            $link->update();
        }

        return Block::query()->where('id', $block->id)->first();
    }
}
