<?php

namespace App\Services\WebsiteService;

use App\Services\WebsiteService\BlockService;

class ProjectService extends BlockService
{
    public function storeBlock($data)
    {
        dd($data);
        return parent::storeBlock($data); // TODO: Change the autogenerated stub
    }
}
